#include <stdio.h>
#include <stdlib.h>
#include <sys/dir.h>
#include <assert.h>
#include <string.h>

#define CRV_IMPLEMENTATION
#include "model.h"

int main(int argc, char* argv[]) {
  if (strcmp(argv[1], "-h") == 0) {
    printf("Usage:\n");
    printf(" pack [-h] [-i input_dir] [-o output_file] [--config] [--block_size] [--num_latents] [--sample_rate]\n");
    printf("\n");
    printf("Options:\n");
    printf(" -h               Display help message.\n");
    printf(" -i input_dir     Specify the input directory.\n");
    printf(" -o output_file   Specify the output file for the packed .bin file.\n");
    printf(" --config         Unique identifier for the model architecture.\n");
    printf(" --block_size     The size of the input/output.\n");
    printf(" --num_latents    Number of latents generated by the encoder.\n");
    printf(" --sample_rate    Sample rate of the dataset the model was trained on.\n");
    printf("\n");
    return 0;
  }

  if (argc < 13) {
    fprintf(stderr, "Error: -h for help.\n"); 
    return 1;
  }

  char* input_dir = NULL;
  char* output_file = NULL;
  char* config = NULL;
  char* block_size = NULL;
  char* num_latents = NULL;
  char* sample_rate = NULL;

  for (int i = 0; i < argc; ++i) {
    if (strcmp(argv[i], "-i") == 0) {
      input_dir = argv[i + 1];
      continue;
    } else if (strcmp(argv[i], "-o") == 0) {
      output_file = argv[i + 1];
      continue;
    } else if (strcmp(argv[i], "--config") == 0) {
      config = argv[i + 1];
      continue;
    } else if (strcmp(argv[i], "--block_size") == 0) {
      block_size = argv[i + 1];
      continue;
    } else if (strcmp(argv[i], "--num_latents") == 0) {
      num_latents = argv[i + 1];
      continue;
    } else if (strcmp(argv[i], "--sample_rate") == 0) {
      sample_rate = argv[i + 1];
    }
  }

  if (!input_dir) {
    fprintf(stderr, "Missing input_dir: -h for help.\n"); 
    return 0;
  } else if (!output_file) {
    fprintf(stderr, "Missing output_file: -h for help.\n"); 
    return 0;
  } else if (!config) {
    fprintf(stderr, "Missing config: -h for help.\n"); 
    return 0;
  } else if (!block_size) {
    fprintf(stderr, "Missing block_size: -h for help.\n"); 
    return 0;
  } else if (!num_latents) {
    fprintf(stderr, "Missing num_latents: -h for help.\n"); 
    return 0;
  } else if (!sample_rate) {
    fprintf(stderr, "Missing sample_rate: -h for help.\n"); 
    return 0;
  }

  header_t header;
  header.size = sizeof(header_t);
  header.config = (uint64_t)strtol(config, NULL, 0);
  header.block_size = (uint32_t)strtol(block_size, NULL, 0);
  header.num_latents = (uint32_t)strtol(num_latents, NULL, 0);
  header.sample_rate = (uint32_t)strtol(sample_rate, NULL, 0);
  header.num_tensors = 0;

  printf("\n");
  printf("input_dir set to:       %s\n", input_dir);
  printf("output_file set to:     %s\n", output_file);
  printf("config set to:          %llu\n", header.config);
  printf("block_size set to:      %u\n", header.block_size);
  printf("num_latents set to:     %u\n", header.num_latents);
  printf("sample_rate set to:     %u\n", header.sample_rate);
  printf("\n");

  size_t alloc_size = 1000 * 1000 * 1000;
  void* memory = malloc(alloc_size);
  if (memory) {
    char* dir_path = input_dir;
    size_t len_dir_path = strlen(dir_path);
    DIR* dir = opendir(dir_path);
    if (dir) {
      FILE* bin = fopen(output_file, "wb");
      if (bin) {
        if (fwrite(&header, sizeof(header_t), 1, bin) == 1) {
          struct dirent* entry = readdir(dir);
          while (entry) {
            char* filename = entry->d_name;
            size_t len_filename = strlen(filename);
            if (len_filename > 4) {
              if (strcmp(filename + len_filename - 4, ".bin") == 0) {
                size_t len_filepath = len_dir_path + len_filename;
                char* filepath = (char*)alloca(len_filepath);
                memset(filepath, 0, len_filepath);
                strcpy(filepath, dir_path);
                strlcat(filepath, filename, len_filepath + 1);
                FILE* file = fopen(filepath, "rb");
                if (file) {
                  printf("Packing: %s\n", filename);
                  fseek(file, 0, SEEK_END);
                  size_t size = ftell(file);
                  fseek(file, 0, SEEK_SET);
                  if (size <= alloc_size) {
                    if (fread(memory, 1, size, file) == size) {
                      if (fwrite(memory, 1, size, bin) == size) {
                        ++header.num_tensors;
                      } else {
                        fprintf(stderr, "Could not write entire file: %s\n", filename);
                      }
                    } else {
                      fprintf(stderr, "Could not read entire file: %s\n", filename);
                    }
                  } else {
                    fprintf(stderr, "File size too large: %s\n", filename);
                  }
                } else {
                  fprintf(stderr, "Couldn't open file: %s\n", filename);
                }
                fclose(file);
              }
            }
            entry = readdir(dir);
          }
          rewind(bin);
          if (fwrite(&header, sizeof(header_t), 1, bin) == 1) {
            printf("Written header.\n");
          } else {
            fprintf(stderr, "Error writing header to file.\n");  
          }
        } else {
          fprintf(stderr, "Couldn't write to model file.\n");
        }
      } else {
        fprintf(stderr, "Couldn't create model file file.\n");
      }
      fclose(bin);
    } else {
      fprintf(stderr, "Couldn't open directory.\n");
    }
    closedir(dir);
  } else {
    fprintf(stderr, "Couldn't allocate memory.\n");
  }
  free(memory);

  return 0;
}
